dataset_name: codex
dataset_path: datasets/codex/multisubgraph_dataset_small.csv
response_model_config:
  model_name: gemini
  params:
    model_id: google/gemini-1.5-flash
    temperature: 1.0
    cache_dir: outputs/responses/
scorer_model_config:
  entity_extractor_model:
    model_name: openai
    params:
      model_id: gpt-4o
      temperature: 1.0
      structured_output: true
      cache_dir: outputs/responses/
  kg_extractor_model:
    model_name: openai
    params:
      model_id: gpt-4o
      temperature: 1.0
      structured_output: true
      cache_dir: outputs/responses/