dataset_name: findkg
data_dir: datasets/findkg
src_node_id_field: subject_id
src_node_type_field: subject_type
src_node_name_field: subject_name
edge_name_field: relation
target_node_id_field: object_id
target_node_type_field: object_type
target_node_name_field: object_name
directed_graph: true

replace_map:
  Positive_Impact_On:
    - Negative_Impact_On
  Negative_Impact_On:
    - Positive_Impact_On
  Raise:
    - Decrease
  Decrease:
    - Raise
