dataset_name: findkg
data_dir: datasets/findkg
src_node_id_field: subject_id
src_node_type_field: subject_type
src_node_name_field: subject_name
edge_name_field: relation
target_node_id_field: object_id
target_node_type_field: object_type
target_node_name_field: object_name
directed_graph: true

replace_map:
  !!python/tuple [CONCEPT, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, ORG/GOV]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, ORG/GOV]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, ORG/GOV]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, ORG/GOV]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, ORG/GOV]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, ORG/GOV]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PERSON, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [FIN_INSTRUMENT, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, ORG/GOV]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, FIN_INSTRUMENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, CONCEPT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, ORG/GOV]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, ORG/GOV]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, GPE]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, ECON_INDICATOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, SECTOR]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [GPE, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/GOV, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, PERSON]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, ORG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [SECTOR, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [PRODUCT, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, PRODUCT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, COMP]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ECON_INDICATOR, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [CONCEPT, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [EVENT, ORG/REG]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [ORG/REG, EVENT]: [Positive_Impact_On, Negative_Impact_On]
  !!python/tuple [COMP, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [GPE, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [PERSON, CONCEPT]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [ORG/REG, CONCEPT]: [Raise, Decrease]
  !!python/tuple [PERSON, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [COMP, CONCEPT]: [Raise, Decrease]
  !!python/tuple [COMP, PRODUCT]: [Raise, Decrease]
  !!python/tuple [GPE, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [GPE, CONCEPT]: [Raise, Decrease]
  !!python/tuple [ORG/REG, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [ORG, CONCEPT]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, CONCEPT]: [Raise, Decrease]
  !!python/tuple [CONCEPT, CONCEPT]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, CONCEPT]: [Raise, Decrease]
  !!python/tuple [ORG, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [GPE, EVENT]: [Raise, Decrease]
  !!python/tuple [ORG/REG, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, ORG/REG]: [Raise, Decrease]
  !!python/tuple [GPE, PERSON]: [Raise, Decrease]
  !!python/tuple [CONCEPT, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [ORG, SECTOR]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, PRODUCT]: [Raise, Decrease]
  !!python/tuple [PRODUCT, CONCEPT]: [Raise, Decrease]
  !!python/tuple [COMP, COMP]: [Raise, Decrease]
  !!python/tuple [ORG, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [PERSON, PERSON]: [Raise, Decrease]
  !!python/tuple [ORG, EVENT]: [Raise, Decrease]
  !!python/tuple [PERSON, ORG]: [Raise, Decrease]
  !!python/tuple [PERSON, SECTOR]: [Raise, Decrease]
  !!python/tuple [PERSON, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [COMP, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, COMP]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [EVENT, CONCEPT]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, PERSON]: [Raise, Decrease]
  !!python/tuple [ECON_INDICATOR, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [ECON_INDICATOR, PERSON]: [Raise, Decrease]
  !!python/tuple [ECON_INDICATOR, ORG]: [Raise, Decrease]
  !!python/tuple [PRODUCT, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [GPE, SECTOR]: [Raise, Decrease]
  !!python/tuple [PERSON, COMP]: [Raise, Decrease]
  !!python/tuple [SECTOR, CONCEPT]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, ORG/REG]: [Raise, Decrease]
  !!python/tuple [ORG, ORG]: [Raise, Decrease]
  !!python/tuple [PERSON, EVENT]: [Raise, Decrease]
  !!python/tuple [CONCEPT, PERSON]: [Raise, Decrease]
  !!python/tuple [PRODUCT, ORG]: [Raise, Decrease]
  !!python/tuple [SECTOR, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, GPE]: [Raise, Decrease]
  !!python/tuple [ORG, ORG/GOV]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, ORG]: [Raise, Decrease]
  !!python/tuple [ECON_INDICATOR, GPE]: [Raise, Decrease]
  !!python/tuple [PERSON, ORG/REG]: [Raise, Decrease]
  !!python/tuple [PERSON, ORG/GOV]: [Raise, Decrease]
  !!python/tuple [ORG, ORG/REG]: [Raise, Decrease]
  !!python/tuple [GPE, ORG/GOV]: [Raise, Decrease]
  !!python/tuple [PRODUCT, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [PERSON, GPE]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, EVENT]: [Raise, Decrease]
  !!python/tuple [CONCEPT, SECTOR]: [Raise, Decrease]
  !!python/tuple [ECON_INDICATOR, CONCEPT]: [Raise, Decrease]
  !!python/tuple [PERSON, PRODUCT]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, COMP]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, GPE]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, PERSON]: [Raise, Decrease]
  !!python/tuple [COMP, ORG/GOV]: [Raise, Decrease]
  !!python/tuple [COMP, SECTOR]: [Raise, Decrease]
  !!python/tuple [COMP, ORG]: [Raise, Decrease]
  !!python/tuple [CONCEPT, EVENT]: [Raise, Decrease]
  !!python/tuple [PRODUCT, PRODUCT]: [Raise, Decrease]
  !!python/tuple [ORG, GPE]: [Raise, Decrease]
  !!python/tuple [ORG, COMP]: [Raise, Decrease]
  !!python/tuple [COMP, PERSON]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, EVENT]: [Raise, Decrease]
  !!python/tuple [COMP, ORG/REG]: [Raise, Decrease]
  !!python/tuple [COMP, EVENT]: [Raise, Decrease]
  !!python/tuple [ECON_INDICATOR, SECTOR]: [Raise, Decrease]
  !!python/tuple [GPE, PRODUCT]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, ORG/GOV]: [Raise, Decrease]
  !!python/tuple [CONCEPT, ORG]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, ORG]: [Raise, Decrease]
  !!python/tuple [ECON_INDICATOR, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, ORG/GOV]: [Raise, Decrease]
  !!python/tuple [ORG/REG, COMP]: [Raise, Decrease]
  !!python/tuple [GPE, GPE]: [Raise, Decrease]
  !!python/tuple [CONCEPT, FIN_INSTRUMENT]: [Raise, Decrease]
  !!python/tuple [ORG, PRODUCT]: [Raise, Decrease]
  !!python/tuple [GPE, ORG]: [Raise, Decrease]
  !!python/tuple [FIN_INSTRUMENT, SECTOR]: [Raise, Decrease]
  !!python/tuple [CONCEPT, GPE]: [Raise, Decrease]
  !!python/tuple [SECTOR, GPE]: [Raise, Decrease]
  !!python/tuple [GPE, COMP]: [Raise, Decrease]
  !!python/tuple [ORG/GOV, SECTOR]: [Raise, Decrease]
  !!python/tuple [SECTOR, SECTOR]: [Raise, Decrease]
  !!python/tuple [SECTOR, PRODUCT]: [Raise, Decrease]
  !!python/tuple [PRODUCT, PERSON]: [Raise, Decrease]
  !!python/tuple [PRODUCT, COMP]: [Raise, Decrease]
  !!python/tuple [GPE, ORG/REG]: [Raise, Decrease]
  !!python/tuple [SECTOR, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [ORG, PERSON]: [Raise, Decrease]
  !!python/tuple [COMP, GPE]: [Raise, Decrease]
  !!python/tuple [CONCEPT, PRODUCT]: [Raise, Decrease]
  !!python/tuple [EVENT, PRODUCT]: [Raise, Decrease]
  !!python/tuple [PRODUCT, SECTOR]: [Raise, Decrease]
  !!python/tuple [EVENT, EVENT]: [Raise, Decrease]
  !!python/tuple [ECON_INDICATOR, PRODUCT]: [Raise, Decrease]
  !!python/tuple [PRODUCT, ORG/GOV]: [Raise, Decrease]
  !!python/tuple [EVENT, ECON_INDICATOR]: [Raise, Decrease]
  !!python/tuple [PRODUCT, GPE]: [Raise, Decrease]
  !!python/tuple [ECON_INDICATOR, ORG/REG]: [Raise, Decrease]
  !!python/tuple [CONCEPT, ORG/REG]: [Raise, Decrease]
  !!python/tuple [EVENT, PERSON]: [Raise, Decrease]
  !!python/tuple [ORG/REG, ORG/GOV]: [Raise, Decrease]
                            