dataset_name: oregano
data_dir: datasets/oregano
src_node_id_field: subject_id
src_node_type_field: subject_type
src_node_name_field: subject_name
edge_name_field: predicate
target_node_id_field: object_id
target_node_type_field: object_type
target_node_name_field: object_name
directed_graph: true

replace_map:
  increase_activity:
    - decrease_activity
  decrease_activity:
    - increase_activity
  increase_effect:
    - decrease_effect
  decrease_effect:
    - increase_effect